# Generated by Django 4.2.20 on 2025-03-14 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador', models.OneToOneField(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='escritorio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('abertura', 'Abertura'), ('alteracao', 'Alteração'), ('transformacao', 'Transformação'), ('baixa', 'Baixa')], max_length=20)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('prazo', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('numero_escritorio', models.PositiveIntegerField()),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app_core.escritorio')),
            ],
        ),
        migrations.CreateModel(
            name='RelacaoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colaboracao', to=settings.AUTH_USER_MODEL)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='app_core.escritorio')),
            ],
        ),
    ]
