# Generated by Django 4.2.20 on 2025-03-14 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('concluido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('prazo', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TarefaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='app_core.anexo')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='app_core.tarefa')),
            ],
            options={
                'unique_together': {('tarefa', 'anexo')},
            },
        ),
        migrations.CreateModel(
            name='TicketTarefaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_escritorio', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tarefa_anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app_core.tarefaanexo')),
            ],
            options={
                'unique_together': {('numero_escritorio', 'tarefa_anexo')},
            },
        ),
    ]
