# Generated by Django 4.2.20 on 2025-03-15 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id_atendimento_escritorio', models.PositiveIntegerField()),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='app_core.escritorio')),
            ],
        ),
    ]
