# Generated by Django 4.2.20 on 2025-03-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='prazo',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tipo',
        ),
    ]
