@startuml
entity Ticket {
    + id: UUID
    + nome_empresa: String
    + tipo: Tipo
    + criado_por: UUID
    + criado_em: DateTime
    + status: Status
    + prazo_conclusao: DateTime
    + urgencia_id: UUID
}

entity Tipo {
    * Abertura
    * Alteracao
    * Transformacao
    * Baixa
}

entity Status {
    * Aberto
    * Andamento
    * Concluido
}

entity Urgencia {
    + id: UUID
    + pq_da_urgencia: Text
    + anexar_comprovante: File
    + qual_prazo_a_ser_comprumprido: xxx
    + concorda_com_pagamento_extra_e_antecipado: xxx
}

entity Timeline {
    + id: UUID
    + ticket_id: UUID
    + data_evento: DateTime
    + descricao: Text
    + criado_por: UUID
}

Ticket --> Tipo
Ticket --> Status
Ticket }o--|| Urgencia : "pode ter"
Ticket ||--o{ Timeline : "possui eventos"
@enduml
