# Generated by Django 4.2.20 on 2025-03-10 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('logomarca', models.ImageField(blank=True, null=True, upload_to='escritorios/logomarcas/')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='escritorios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
